// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuuzmuxyiessejxsrzjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dXptdXh5aWVzc2VqeHNyempsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTI4ODQsImV4cCI6MjA2NTA2ODg4NH0.UfQg8NH5S7T5V8Ro7BEDLYYF-4t6y5AbGYjUZwcnpE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);